---
title: "Bayesian Linear Analysis"
author: "Megan Feddern"
date: "2023-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nord)
library(tidyr)
library(lubridate)
library(readr)
library(stringr)
library(ggplot2)
library(cowplot)
library(Cairo)
library(MCMCvis)
library(HDInterval)
library(reshape2)
library(tidyverse)
library(dplyr)
library(rstan)
library(car)
```

## Combining Bakun Data
1) Import the Bakun upwelling data from each individual file associated with the 13 lat/long locations. Data versions are: 1˚ 6-hourly version

```{r import}
bakundat <- read.csv('Data/physical/Bakun/erdUI246hr_d68d_e898_8529.csv')%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI276hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI306hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI336hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI366hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI396hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI426hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI456hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI486hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI516hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI546hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI576hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI606hr_d68d_e898_8529.csv'))%>%
  bind_rows(read.csv('Data/physical/Bakun/erdUI616hr_d68d_e898_8529.csv'))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
